name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: create a ZIP file
        run: ls &&
          zip -r sukkiri-servlet2-codes.zip README/* chap*/* LICENSE.txt README.md &&
          unzip -t sukkiri-servlet2-codes.zip
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          files: sukkiri-servlet2-codes.zip
          draft: false
          prerelease: false
